export const workspaceCopy = {
  en: {
    "workspace.import": "Import",
    "workspace.analyze": "Analyze",
    "workspace.review": "Review",
    "workspace.export": "Export",
    "workspace.local": "On your device",
    "workspace.workflow": "Culling workflow",
    "import.title": "More moments.\nFewer duplicates.",
    "import.description":
      "Turn a day of competition photos into a considered selection. Start with your camera cards; make the final call on every frame.",
    "import.step1": "Bring your cards together",
    "import.step1Hint": "Add one or more folders. Subfolders are included.",
    "import.step2": "Find the frames that matter",
    "import.step2Hint": "Check quality scores and compare similar shots.",
    "import.step3": "Leave with an organized set",
    "import.step3Hint": "Copy your selections into clearly labeled folders.",
    "import.newSession": "New session",
    "import.sources": "Photo sources",
    "import.sourcesHint": "Choose folders from your computer or an SD card.",
    "import.add": "Add folders",
    "import.addMore": "Add another folder",
    "import.formats": "JPG & JPEG · Includes subfolders",
    "import.empty": "Your next selection starts here",
    "import.emptyHint": "Add a photo folder to prepare your session.",
    "import.folderCount": "{n} folders added",
    "import.remove": "Remove {name}",
    "import.destination": "Export destination",
    "import.destinationHint":
      "Your originals stay where they are. Export creates copies.",
    "import.defaultDestination": "Default: Pictures/FYF Photo Culler",
    "import.change": "Choose",
    "import.mergeHint": "Combine cards in one set of category folders.",
    "import.ready": "Ready when you are",
    "import.startHint": "Add a folder to enable analysis.",
    "import.safe": "Local processing. Originals untouched.",
    "import.path": "Full folder path",
    "import.pathHint":
      "Enter a local folder path, for example /Users/you/Pictures",
    "import.pathAdd": "Add",
    "import.skipped":
      "{n} unsupported files will be skipped. Only JPG and JPEG photos are analyzed.",
    "import.continue": "Analyze JPEG photos",
    "import.replace":
      "Starting a new session replaces the saved review. Your original photos are unaffected.",
    "import.replaceAction": "Start new session",
    "import.cancel": "Cancel",
    "import.failed":
      "Could not open the folder. Try again or enter its full path.",
    "import.startFailed":
      "Could not start analysis. Check that your folders are accessible and try again.",
    "review.heading": "Your contact sheet",
    "review.subtitle": "Suggested by analysis. Decided by you.",
    "review.all": "All photos",
    "review.importMore": "Photo sources",
    "review.inspectHint": "Click to inspect · Double-click to enlarge",
    "review.loadFailed": "Photos could not be loaded.",
    "review.loadHint":
      "Check the connection to the analysis engine, then try again.",
    "review.retry": "Try again",
    "review.resetFilters": "Clear filters",
    "review.selection": "Select {name}",
    "review.imageFailed": "Preview unavailable",
    "review.loaded": "{n} photos loaded",
    "review.allLoaded": "All {n} photos loaded",
    "review.loadMore": "Load more photos",
    "review.decisions": "Keep / Maybe / Reject",
    "review.close": "Close",
    "review.shutter": "Shutter",
    "review.aperture": "Aperture",
    "review.small": "Small thumbnails",
    "review.medium": "Medium thumbnails",
    "review.large": "Large thumbnails",
    "processing.hint":
      "Checking focus, exposure and similar frames. You will review the suggestions next.",
    "processing.connectionLost":
      "Connection to the analysis engine was lost. Return to your sources to try again.",
    "processing.cancelError": "Could not cancel. Try again.",
    "processing.resultError":
      "Analysis finished, but the results could not be loaded. Return to your sources and resume the saved session.",
    "export.description":
      "One last look before your photos are copied into organized folders.",
    "export.copyNote":
      "All categories are copied, including rejected photos. Nothing is deleted or moved.",
    "export.previewError":
      "Could not load the export summary. Try again before exporting.",
    "export.connectionLost":
      "Connection lost during export. Some files may have been copied. Check the destination before retrying.",
    "export.openError":
      "Could not open the folder. Use the path below to find your exported photos.",
    "export.ready": "Ready to export",
    "export.newSession": "New session",
    "export.total": "{n} photos to copy",
    "export.loading": "Preparing export summary…",
    "export.defaultHint": "Pictures/FYF Photo Culler",
    "export.outputHint": "Set when this session was created.",
    "theme.toggle": "Switch color theme",
    "language.toggle": "Türkçeye geç",
  },
  tr: {
    "workspace.import": "İçe aktar",
    "workspace.analyze": "Analiz et",
    "workspace.review": "İncele",
    "workspace.export": "Dışa aktar",
    "workspace.local": "Bu cihazda",
    "workspace.workflow": "Fotoğraf eleme adımları",
    "import.title": "Anlar kalsın.\nTekrarlar elensin.",
    "import.description":
      "Yarışma boyunca çekilen fotoğraflardan özenli bir seçki oluştur. Kamera kartlarını ekle; her karede son kararı sen ver.",
    "import.step1": "Kartlarını bir araya getir",
    "import.step1Hint":
      "Bir veya daha fazla klasör ekle. Alt klasörler de taranır.",
    "import.step2": "Öne çıkan kareleri bul",
    "import.step2Hint":
      "Kalite puanlarını incele, benzer çekimleri karşılaştır.",
    "import.step3": "Düzenli bir seçkiyle tamamla",
    "import.step3Hint":
      "Fotoğrafların, kararlarına göre klasörlere kopyalansın.",
    "import.newSession": "Yeni oturum",
    "import.sources": "Fotoğraf kaynakları",
    "import.sourcesHint": "Bilgisayarından veya SD kartından klasör seç.",
    "import.add": "Klasör ekle",
    "import.addMore": "Başka klasör ekle",
    "import.formats": "JPG ve JPEG · Alt klasörler dahil",
    "import.empty": "Bir sonraki seçkin burada başlıyor",
    "import.emptyHint": "Oturumunu hazırlamak için bir fotoğraf klasörü ekle.",
    "import.folderCount": "{n} klasör eklendi",
    "import.remove": "{name} klasörünü kaldır",
    "import.destination": "Dışa aktarma konumu",
    "import.destinationHint":
      "Orijinaller yerinde kalır. Dışa aktarırken kopyaları oluşturulur.",
    "import.defaultDestination": "Varsayılan: Pictures/FYF Photo Culler",
    "import.change": "Seç",
    "import.mergeHint": "Kartları ortak kategori klasörlerinde birleştir.",
    "import.ready": "Hazır olduğunda başlayalım",
    "import.startHint": "Analize başlamak için bir klasör ekle.",
    "import.safe": "Analiz bu cihazda yapılır. Orijinaller korunur.",
    "import.path": "Tam klasör yolu",
    "import.pathHint": "Yerel klasör yolunu gir, örneğin /Users/adın/Pictures",
    "import.pathAdd": "Ekle",
    "import.skipped":
      "{n} desteklenmeyen dosya atlanacak. Yalnızca JPG ve JPEG fotoğraflar analiz edilir.",
    "import.continue": "JPEG fotoğrafları analiz et",
    "import.replace":
      "Yeni oturum, kayıtlı incelemenin yerini alır. Orijinal fotoğrafların etkilenmez.",
    "import.replaceAction": "Yeni oturum başlat",
    "import.cancel": "Vazgeç",
    "import.failed":
      "Klasör açılamadı. Tekrar dene veya tam klasör yolunu gir.",
    "import.startFailed":
      "Analiz başlatılamadı. Klasörlerin erişilebilir olduğunu kontrol edip tekrar dene.",
    "review.heading": "Fotoğraf seçkin",
    "review.subtitle": "Analiz önerir. Sen karar verirsin.",
    "review.all": "Tüm fotoğraflar",
    "review.importMore": "Fotoğraf kaynakları",
    "review.inspectHint": "İncelemek için tıkla · Büyütmek için çift tıkla",
    "review.loadFailed": "Fotoğraflar yüklenemedi.",
    "review.loadHint": "Analiz motoru bağlantısını kontrol edip tekrar dene.",
    "review.retry": "Tekrar dene",
    "review.resetFilters": "Filtreleri temizle",
    "review.selection": "{name} fotoğrafını seç",
    "review.imageFailed": "Önizleme kullanılamıyor",
    "review.loaded": "{n} fotoğraf yüklendi",
    "review.allLoaded": "{n} fotoğrafın tamamı yüklendi",
    "review.loadMore": "Daha fazla fotoğraf yükle",
    "review.decisions": "Tut / Belki / Reddet",
    "review.close": "Kapat",
    "review.shutter": "Enstantane",
    "review.aperture": "Diyafram",
    "review.small": "Küçük önizlemeler",
    "review.medium": "Orta önizlemeler",
    "review.large": "Büyük önizlemeler",
    "processing.hint":
      "Netlik, pozlama ve benzer kareler kontrol ediliyor. Ardından önerileri sen inceleyeceksin.",
    "processing.connectionLost":
      "Analiz motoruyla bağlantı kesildi. Tekrar denemek için fotoğraf kaynaklarına dön.",
    "processing.cancelError": "İptal edilemedi. Tekrar dene.",
    "processing.resultError":
      "Analiz tamamlandı ancak sonuçlar yüklenemedi. Kaynaklara dönüp kayıtlı oturumu sürdür.",
    "export.description":
      "Fotoğrafların düzenli klasörlere kopyalanmadan önce son bir kontrol.",
    "export.copyNote":
      "Reddedilenler dahil tüm kategoriler kopyalanır. Hiçbir fotoğraf silinmez veya taşınmaz.",
    "export.previewError":
      "Dışa aktarma özeti yüklenemedi. Devam etmeden önce tekrar dene.",
    "export.connectionLost":
      "Aktarım sırasında bağlantı kesildi. Bazı dosyalar kopyalanmış olabilir. Tekrar denemeden önce hedef klasörü kontrol et.",
    "export.openError":
      "Klasör açılamadı. Dışa aktarılan fotoğrafları aşağıdaki yoldan bulabilirsin.",
    "export.ready": "Dışa aktarmaya hazır",
    "export.newSession": "Yeni oturum",
    "export.total": "{n} fotoğraf kopyalanacak",
    "export.loading": "Dışa aktarma özeti hazırlanıyor…",
    "export.defaultHint": "Pictures/FYF Photo Culler",
    "export.outputHint": "Bu oturum oluşturulurken belirlendi.",
    "theme.toggle": "Renk temasını değiştir",
    "language.toggle": "Switch to English",
  },
} as const;
